// Reused business assertions from the completed 2026-10-09 NOTE1 audit.
const {chromium}=require('playwright');const fs=require('fs'),assert=require('node:assert/strict');const out=require('./support.cjs').out,url=require('./support.cjs').url;const results=[];
(async()=>{const browser=await chromium.launch(require('./support.cjs').launchOptions);const ctx=await browser.newContext();const page=await ctx.newPage();page.setDefaultTimeout(4000);const b=n=>page.getByRole('button',{name:n,exact:true});
const state=()=>page.evaluate(()=>new Promise((res,rej)=>{const r=indexedDB.open('ianyu-note1-web');r.onsuccess=()=>{const db=r.result,q=db.transaction('state').objectStore('state').get('data');q.onsuccess=()=>{res(q.result);db.close()}};r.onerror=()=>rej(r.error)}));
const nav=async p=>{await page.goto(url+'?boundary='+Date.now()+'#/'+p);await page.waitForTimeout(250)};
const test=async(id,fn)=>{try{results.push({id,status:'passed',detail:await fn()});console.log('PASS',id)}catch(e){results.push({id,status:'failed',error:String(e)});fs.writeFileSync(out+'/'+id+'.aria.txt',await page.locator('body').ariaSnapshot());console.log('FAIL',id,String(e))}fs.writeFileSync(out+'/boundary-results.json',JSON.stringify(results,null,2))};
const create=async t=>{await b('记录灵感').click();await page.getByRole('textbox',{name:'灵感内容',exact:true}).fill(t);await b('保存').click();await page.getByRole('dialog').waitFor({state:'hidden'})};
await nav('');
await test('W28-six-active-collections',async()=>{for(let i=1;i<=6;i++){await b('灵感').click();await create('CAP group '+i);await b('卡片预览').click();await b('归入构思集').click();await page.getByRole('textbox',{name:'构思集名称',exact:true}).fill('CAP-'+i);await b('创建并归入').click();await page.getByRole('dialog').waitFor({state:'hidden'})}assert.equal((await state()).collections.length,6)});
await test('W29-eleven-members-reload',async()=>{for(let i=2;i<=11;i++){await b('灵感').click();await create('CAP member '+i);await b('卡片预览').click();await b('归入构思集').click();await page.getByRole('button',{name:/^CAP-1 \d+ 条灵感$/}).click();await page.getByRole('dialog').waitFor({state:'hidden'})}await page.reload();await b('记录灵感').waitFor();const s=await state();const c=s.collections.find(x=>x.name==='CAP-1');assert.equal(s.rounds.find(x=>x.id===c.currentRoundId).memberIds.length,11);assert.equal(s.collections.length,6);fs.writeFileSync(out+'/capacity-state.json',JSON.stringify(s,null,2));});
await test('W30-workbench-edit-order-remove',async()=>{await b('构思集').click();await page.getByRole('button',{name:/^CAP-1 /}).click();await page.getByRole('textbox',{name:'编辑当前灵感',exact:true}).fill('CAP edited');await b('下一条灵感').click();assert.ok((await state()).inspirations.some(x=>x.text==='CAP edited'));await b('构思集更多操作').click();await b('概览与排序').click();let s=await state();const c=s.collections.find(x=>x.name==='CAP-1');const ids=s.rounds.find(x=>x.id===c.currentRoundId).memberIds;await b('下移').first().click();await page.waitForTimeout(200);s=await state();assert.equal(s.rounds.find(x=>x.id===c.currentRoundId).memberIds[1],ids[0]);await b('移出构思集').first().click();await page.waitForTimeout(200);s=await state();assert.equal(s.rounds.find(x=>x.id===c.currentRoundId).memberIds.length,10)});
await test('W31-generation-persistence-failure',async()=>{await b('结束本轮构思').click();const before=await state();await page.evaluate(()=>{const old=IDBDatabase.prototype.transaction;window.undoFault=()=>IDBDatabase.prototype.transaction=old;IDBDatabase.prototype.transaction=function(n,m,...a){if(m==='readwrite')throw new DOMException('Injected write failure','QuotaExceededError');return old.call(this,n,m,...a)}});await b('生成小票').click();await page.getByRole('alert').waitFor();assert.deepEqual(await state(),before);assert.equal(await b('生成小票').isEnabled(),true);await page.evaluate(()=>window.undoFault());await b('取消').click()});
await test('W32-double-generate-unique',async()=>{await b('结束本轮构思').click();await b('生成小票').evaluate(el=>{el.click();el.click()});for(let i=0;i<30&&(await state()).receipts.length===0;i++)await page.waitForTimeout(100);assert.equal((await state()).receipts.length,1);await page.reload();await page.waitForTimeout(300);assert.equal((await state()).receipts.length,1)});
await test('W33-attachment-backup-byte-readback',async()=>{await nav('settings');await page.locator('input[type=file]').setInputFiles(out+'/backup.json');await b('恢复并替换当前数据').click();await page.getByRole('dialog').waitFor({state:'hidden'});const backup=JSON.parse(fs.readFileSync(out+'/backup.json','utf8'));const s=await state();assert.deepEqual(s,backup.data);const actual=await page.evaluate(()=>new Promise((res,rej)=>{const r=indexedDB.open('ianyu-note1-web');r.onsuccess=()=>{const db=r.result,q=db.transaction('resourceBlobs').objectStore('resourceBlobs').getAll();q.onsuccess=async()=>{try{res(await Promise.all(q.result.map(async b=>{const blob=b.blob||b;return await blob.text()})));db.close()}catch(e){rej(String(e))}}}}));assert.ok(actual.includes('NOTE1 attachment immutable evidence 20261009'));return actual});
await test('W34-future-schema-readonly',async()=>{await page.evaluate(()=>new Promise(res=>{const r=indexedDB.open('ianyu-note1-web');r.onsuccess=()=>{const db=r.result,tx=db.transaction('meta','readwrite');tx.objectStore('meta').put({schemaVersion:999,initializedAt:new Date().toISOString()},'root');tx.oncomplete=()=>{db.close();res()}}}));const before=await state();await page.reload();await page.getByText('本地数据版本过新，请更新页面。',{exact:true}).waitFor();assert.equal(await b('记录灵感').count(),0);assert.deepEqual(await state(),before)});
await browser.close()})();
